#  SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#  SPDX-FileCopyrightText: 2020 - 2021 STA <info@sta.bz.it>

# SPDX-License-Identifier: AGPL-3.0-or-later

@host={{$dotenv NINJA_BASE_PATH}}

###
GET {{host}}/flat/EChargingStation

###
GET {{host}}/flat/EChargingStation,EChargingPlug?select=scode,smetadata.outlets,smetadata.connectors&where=sactive.eq.true,pactive.eq.true&distinct=true&shownull=false&offset=0&limit=-1&origin=webcomp-mobility-echarging-dashboard



###
GET {{host}}/flat/EChargingStation?where=sorigin.eq.ALPERIA&limit=1
###
GET {{host}}/flat/EChargingPlug?where=sorigin.eq.Neogy&limit=5

ALPERIA
DRIWE
DRIWE-OCPI
IIT
Neogy
Nevicam
route220

###

GET {{host}}/flat/EChargingPlug?where=sorigin.eq.ALPERIA&limit=5