version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/code
    working_dir: /code
    command: sh ./work/serve.sh
    ports:
      - "8999:8000"
    tty: true
