# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
# SPDX-FileCopyrightText: 2020 - 2021 STA <info@sta.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3"
services:
  app:
    build:
      context: .
      dockerfile: infrastructure/docker/node.dockerfile
    volumes:
      - ./:/code
    working_dir: /code
    command: sh -c "test -d node_modules || npm install; npm run start"
    ports:
      - "8999:8999"
    tty: true
