version: "3"
services:
  app:
    build:
      context: .
      dockerfile: infrastructure/docker/node.dockerfile
    volumes:
      - ./:/code
    working_dir: /code
    command: sh -c "test -d node_modules || yarn; yarn start"
    ports:
      - "8999:8000"
    tty: true
