version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/code
    working_dir: /code
    command: yarn run start
    ports:
      - "8000:8000"
    tty: true
