@host=https://mobility.api.opendatahub.bz.it/v2
#@host=http://localhost:8081


### TESTING....

GET {{host}}/flat/EChargingPlug/echarging-plug-status/latest
?sactive.eq.true,scoordinate.bbi.(10.380587,46.219386,12.479683,47.097544)
&limit=-1
&offset=0
&select=scode,pcode,mvalue

###
GET {{host}}/flat/EChargingStation
?select=count(scode)
#&where=sactive.eq.true
&distinct=false

###
GET {{host}}/tree/EChargingPlug/echarging-plug-status/latest
#?select=count(pcode)
?select=pcode,pmetadata.state,mvalue
&where=sactive.eq.true,pactive.eq.true
#,scoordinate.bbi.(10.380587,46.219386,12.479683,47.097544)
&limit=-1

###
GET {{host}}/flat/EChargingPlug/echarging-plug-status/latest
?select=mvalue,pname,pcode,sname,smetadata,pmetadata
#,smetadata, pcode
#count(pcode)
&where=pactive.eq.true,pname.eq."CR_ALTA_VALSUGANA_04"


###
GET {{host}}/flat/EChargingStation
?select=smetadata.state
&where=sactive.eq.true
&limit=-1

###
GET {{host}}/flat/EChargingPlug/echarging-plug-status/latest
?limit=-1
&select=pcode,count(mvalue)
&where=sactive.eq.true,pactive.eq.true
&shownull=false
&distinct=true

###
GET {{host}}/flat/EChargingPlug/echarging-plug-status
?select=smetadata

######################## OVERVIEW ###############################################################################
# See src/api/integreen-life.js and src/api/integreen-life-requests.js for details

### CHART1: Charging station in operation (percentage)
# Uses request__get_stations_details

### CHART3: Type of plugs
# Uses request__get_plugs_details and request_plug_types

### CHART5: Access to charging stations (percentages)
# Uses request_charging_stations_access_types and request__get_stations_details

### CHART6: Plugs in operation (percentage)
# Uses request_plugs_with_state_and_echargingstation

######################### REQUESTS ##############################################################################
# See src/api/integreen-life-requests.js for details
# FOR BOLZANO-ONLY-CALLS: Just add scoordinate.bbi.(10.380587,46.219386,12.479683,47.097544) to the WHERE clause

### request__get_stations_details
GET {{host}}/flat/EChargingStation?select=scode,smetadata.state,smetadata.accessType&limit=-1&offset=0&where=sactive.eq.true&shownull=false&distinct=true

### request__get_plugs_details
GET {{host}}/flat/EChargingStation,EChargingPlug?select=scode,smetadata.outlets&limit=-1&offset=0&where=sactive.eq.true&shownull=false&distinct=true

### request__at_least_one_plug_used_active_count (NEW)
GET {{host}}/flat/EChargingPlug/echarging-plug-status/latest?select=count(pcode)&where=sactive.eq.true,mvalue.eq.0

### request_plug_types (NEW)
GET {{host}}/flat/EChargingPlug?limit=-1&offset=0&select=smetadata.outlets.0.outletTypeCode&where=sactive.eq.true,smetadata.outlets.0.outletTypeCode.neq.UNKNOWN&shownull=false&distinct=true

### request_charging_stations_access_types
GET {{host}}/flat/EChargingStation?limit=-1&offset=0&select=smetadata.accessType&where=sactive.eq.true&shownull=false&distinct=true

### request_plugs_with_state_and_echargingstation
GET {{host}}/flat/EChargingPlug/echarging-plug-status/latest?select=scode,pcode,mvalue&limit=-1&offset=0&where=sactive.eq.true&shownull=false&distinct=true

################################ JUST TESTING (PLEASE IGNORE) #######################################

### T1
GET https://mobility.api.opendatahub.bz.it/v2/flat/EChargingStation?limit=-1&offset=0&where=sactive.eq.true,scoordinate.bbi.(10.380587,46.219386,12.479683,47.097544)&shownull=false&distinct=true

### T2
GET https://mobility.api.opendatahub.bz.it/v2/flat/EChargingStation,EChargingPlug?limit=-1&offset=0&where=sactive.eq.true&shownull=false&distinct=true

### T3
GET https://mobility.api.opendatahub.bz.it/v2/flat/EChargingStation?select=scode,smetadata.accessType,smetadata.state

